### ISSUE TITLE
jupyter notebook syntax error

### ISSUE THREAD

**Issue by git-adeeba** [mcmahon-lab/Physics-Aware-Training#2]
_Error for syntax even thought the code is correct_ ( Editor used - Jupyter notebook )
**code written** : first_name = "Jack"
                             print(first_name)
                   
**Error shown** :                     

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-ba361b11d0f1> in <module>
      1 # Exercise 3
----> 2 print(first_name)

NameError: name 'first_name' is not defined

**Comment by ms3452** [comment]
This seems to be an issue unrelated to this repository and I will therefore close it. Please refer to the jupyter notebook repository at https://github.com/jupyter/notebook.

**Comment by git-adeeba** [comment]
Yeah am extremely sorry for that , I am new to Github and didn't know where to post and later realized I've posted the issue in a wrong repository . Thanks for the info

**Comment by ms3452** [comment]
No worries. I wasn't sure where to refer you to but I hope you found the information you were searching for.
